(define (p151)
  (letrec ((iter (lambda (a b c d)
                   (cond ((and (= a 1) (= b c d 0)) 
                          (+ 1 (iter 0 1 1 1)))
                         ((and (= b 1) (= a c d 0)) 
                          (+ 1 (iter 0 0 1 1)))
                         ((and (= c 1) (= a b d 0)) 
                          1)  
                         ((and (= d 1) (= a b c 0)) 
                          0)  
                         (else
                           (/ (+ (if (> a 0) (* (iter (- a 1) (+ b 1) (+ c 1) (+ d 1)) a) 0)
                                 (if (> b 0) (* (iter a (- b 1) (+ c 1) (+ d 1)) b) 0)
                                 (if (> c 0) (* (iter a b (- c 1) (+ d 1)) c) 0)
                                 (if (> d 0) (* (iter a b c (- d 1)) d) 0)) 
                              (+ a b c d)))))))
    (exact->inexact (iter 1 1 1 1))))

(print (p151))
